enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

[mode.main.binding]
alt-enter = 'exec-and-forget open -na Ghostty'
alt-j = 'focus left'
alt-k = 'focus down'
alt-l = 'focus up'
alt-semicolon = 'focus right'

alt-shift-j = 'move left'
alt-shift-k = 'move down'
alt-shift-l = 'move up'
alt-shift-semicolon = 'move right'

cmd-alt-h = 'split horizontal'
cmd-alt-v = 'split vertical'

cmd-alt-f = 'fullscreen'

cmd-alt-s = 'layout v_accordion' # 'layout stacking' in i3
cmd-alt-w = 'layout h_accordion' # 'layout tabbed' in i3

cmd-alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

cmd-alt-m = 'move-workspace-to-monitor --wrap-around next'

cmd-alt-space = 'layout floating tiling'

# switch between workspaces
alt-tab = 'workspace-back-and-forth'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

cmd-alt-1 = 'workspace 11'
cmd-alt-2 = 'workspace 12'
cmd-alt-3 = 'workspace 13'
cmd-alt-4 = 'workspace 14'
cmd-alt-5 = 'workspace 15'
cmd-alt-6 = 'workspace 16'
cmd-alt-7 = 'workspace 17'
cmd-alt-8 = 'workspace 18'
cmd-alt-9 = 'workspace 19'
cmd-alt-0 = 'workspace 20'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

cmd-alt-shift-1 = 'move-node-to-workspace 11'
cmd-alt-shift-2 = 'move-node-to-workspace 12'
cmd-alt-shift-3 = 'move-node-to-workspace 13'
cmd-alt-shift-4 = 'move-node-to-workspace 14'
cmd-alt-shift-5 = 'move-node-to-workspace 15'
cmd-alt-shift-6 = 'move-node-to-workspace 16'
cmd-alt-shift-7 = 'move-node-to-workspace 17'
cmd-alt-shift-8 = 'move-node-to-workspace 18'
cmd-alt-shift-9 = 'move-node-to-workspace 19'
cmd-alt-shift-0 = 'move-node-to-workspace 20'

alt-shift-c = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
j = 'resize width -50'
k = 'resize height +50'
l = 'resize height -50'
semicolon = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

# custom window rules

# finder
[[on-window-detected]]
    if.app-name-regex-substring = 'finder'
    run = ['layout floating']

# wip-* windows
[[on-window-detected]]
    if.window-title-regex-substring = 'wip-.*'
    run = ['layout floating']
